name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        type: choice
        options:
          - pc
          - laptop

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || 'pc' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Replace API_URL placeholder with backend address
        run: |
          sed -i "s|__API_URL__|${{ vars.API_BACKEND_URL }}|g" ./frontend/app.js

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Frontend as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./frontend

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
